name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Java 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'	  
        java-version: 21
    - name: Build with Java 21
      working-directory: ./query
      run: ../mvnw -B clean test --file pom.xml